const loadEventsConfig = {
	targetEvents:
		[
			{ target: 'entity',
				version: 0,
				entityId: '123',
				metadata: { command: 'asOneCmd', initiatorId: '999888777' },
				operation: 'created',
				entityName: 'Person' },
			{ target: 'entity',
				version: 0,
				entityId: '456',
				metadata: { command: 'asOneCmd', initiatorId: '999888777' },
				operation: 'created',
				entityName: 'Person' },
			{ target: 'entity',
				version: 0,
				entityId: '789',
				metadata: { command: 'asOneCmd', initiatorId: '999888777' },
				operation: 'created',
				entityName: 'Address' },
			{ target: 'entity',
				version: 0,
				entityId: '1111',
				metadata: { command: 'asOneCmd', initiatorId: '999888777' },
				operation: 'created',
				entityName: 'Address' },
			{ target: 'entity',
				version: 0,
				entityId: '2222',
				metadata: { command: 'asOneCmd', initiatorId: '999888777' },
				operation: 'created',
				entityName: 'Address' },
			{ value: { first: 'Joe', middle: '', last: 'Mama' },
				target: 'property',
				version: 0,
				entityId: '123',
				metadata: { command: 'asOneCmd', initiatorId: '999888777' },
				operation: 'added',
				entityName: 'Person',
				propertyName: 'name' },
			{ value: { first: 'Mickey', middle: '', last: 'Mouse' },
				target: 'property',
				version: 0,
				entityId: '456',
				metadata: { command: 'asOneCmd', initiatorId: '999888777' },
				operation: 'added',
				entityName: 'Person',
				propertyName: 'name' },
			{ value: 'Main Street',
				target: 'property',
				version: 0,
				entityId: '789',
				metadata: { command: 'asOneCmd', initiatorId: '999888777' },
				operation: 'added',
				entityName: 'Address',
				propertyName: 'street' },
			{ target: 'relationship',
				version: 0,
				entityId: '456',
				metadata: { command: 'asOneCmd', initiatorId: '999888777' },
				operation: 'added',
				entityName: 'Person',
				propertyName: 'address',
				relationshipId: '789' },
			{ target: 'relationship',
				version: 0,
				entityId: '456',
				metadata: { command: 'asOneCmd', initiatorId: '999888777' },
				operation: 'removed',
				entityName: 'Person',
				propertyName: 'address' },
			{ value: 'Joe Blow',
				target: 'propertyList',
				version: 0,
				entityId: '123',
				metadata: { command: 'asOneCmd', initiatorId: '999888777' },
				operation: 'added',
				entityName: 'Person',
				propertyId: '9001',
				propertyName: 'aliases' },
			{ value: 'Joe Cool',
				target: 'propertyList',
				version: 0,
				entityId: '123',
				metadata: { command: 'asOneCmd', initiatorId: '999888777' },
				operation: 'added',
				entityName: 'Person',
				propertyId: '9002',
				propertyName: 'aliases' },
			{ value: 'Joey Joe',
				target: 'propertyList',
				version: 0,
				entityId: '123',
				metadata: { command: 'asOneCmd', initiatorId: '999888777' },
				operation: 'added',
				entityName: 'Person',
				propertyId: '9003',
				propertyName: 'aliases' },
			{ target: 'propertyList',
				version: 0,
				entityId: '123',
				metadata: { command: 'asOneCmd', initiatorId: '999888777' },
				operation: 'positioned',
				entityName: 'Person',
				newPosition: 0,
				oldPosition: 1,
				propertyName: 'aliases' },
			{ target: 'relationshipList',
				version: 0,
				entityId: '123',
				metadata: { command: 'asOneCmd', initiatorId: '999888777' },
				operation: 'added',
				entityName: 'Person',
				propertyId: '8001',
				propertyName: 'oldAddresses',
				relationshipId: '1111' },
			{ target: 'relationshipList',
				version: 0,
				entityId: '123',
				metadata: { command: 'asOneCmd', initiatorId: '999888777' },
				operation: 'added',
				entityName: 'Person',
				propertyId: '8002',
				propertyName: 'oldAddresses',
				relationshipId: '2222' },
			{ target: 'relationshipList',
				version: 0,
				entityId: '123',
				metadata: { command: 'asOneCmd', initiatorId: '999888777' },
				operation: 'positioned',
				entityName: 'Person',
				newPosition: 0,
				oldPosition: 1,
				propertyName: 'oldAddresses' },
			{ target: 'entity',
				version: 0,
				entityId: '123',
				metadata: { command: 'asOneCmd', initiatorId: '999888777' },
				operation: 'destroyed',
				entityName: 'Person' },
			{ target: 'entity',
				entityId: '9f43b56e-ed00-4a47-bd67-575fe11ad519',
				metadata: { command: 'User.create', initiatorId: '1' },
				operation: 'created',
				entityName: 'User' },
			{ value: 'joeblow2',
				target: 'property',
				entityId: '9f43b56e-ed00-4a47-bd67-575fe11ad519',
				metadata: { command: 'User.create', initiatorId: '1' },
				operation: 'added',
				entityName: 'User',
				propertyName: 'username' },
			{ value: 'joe@aol.com',
				target: 'property',
				entityId: '9f43b56e-ed00-4a47-bd67-575fe11ad519',
				metadata: { command: 'User.initializeAuthenticationMethod', initiatorId: '1' },
				operation: 'added',
				entityName: 'User',
				propertyName: 'email' },
			{ value: 'Email',
				target: 'property',
				entityId: '9f43b56e-ed00-4a47-bd67-575fe11ad519',
				metadata: { command: 'User.initializeAuthenticationMethod', initiatorId: '1' },
				operation: 'added',
				entityName: 'User',
				propertyName: 'authenticationMethod' },
			{ value: 'joeblow3',
				target: 'property',
				entityId: '9f43b56e-ed00-4a47-bd67-575fe11ad519',
				metadata: { command: 'User.changeUserame', initiatorId: '1' },
				operation: 'added',
				entityName: 'User',
				propertyName: 'username' },
			{ value: 'joe',
				target: 'property',
				entityId: '9f43b56e-ed00-4a47-bd67-575fe11ad519',
				metadata: { command: 'User.changeName', initiatorId: '1' },
				operation: 'added',
				entityName: 'User',
				propertyName: 'name' },
			{ target: 'property',
				entityId: '9f43b56e-ed00-4a47-bd67-575fe11ad519',
				metadata: { command: 'User.removeName', initiatorId: '1' },
				operation: 'removed',
				entityName: 'User',
				propertyName: 'name' },
			{ target: 'entity',
				entityId: '9f43b56e-ed00-4a47-bd67-575fe11ad519',
				metadata: { command: 'User.destroy', initiatorId: '1' },
				operation: 'destroyed',
				entityName: 'User' } ],
		fillerEvents:
		[
			{ target: 'entity',
				version: 0,
				entityId: '',
				metadata: { command: 'asOneCmd', initiatorId: '' },
				operation: 'created',
				entityName: 'Filler' },
			{ target: 'entity',
				version: 0,
				entityId: '',
				metadata: { command: 'asOneCmd', initiatorId: '' },
				operation: 'added',
				entityName: 'Filler' },
			{ target: 'entity',
				version: 0,
				entityId: '',
				metadata: { command: 'asOneCmd', initiatorId: '' },
				operation: 'removed',
				entityName: 'Filler' },
			{ value: 'joeblow3',
				target: 'property',
				entityId: '',
				metadata: { command: 'User.changeUserame', initiatorId: '' },
				operation: 'added',
				entityName: 'Filler',
				propertyName: 'fillername' },
			{ value: 'joeblow3',
				target: 'property',
				entityId: '',
				metadata: { command: 'User.changeUserame', initiatorId: '' },
				operation: 'removed',
				entityName: 'Filler',
				propertyName: 'fillername' }
		]
};
module.exports = loadEventsConfig;